cmake_minimum_required(VERSION 3.0.2)
project(h5_udp_bridge)

find_package(catkin REQUIRED COMPONENTS
  rospy
  std_msgs
  sensor_msgs
  mainpulator
)

catkin_package(CATKIN_DEPENDS rospy std_msgs sensor_msgs mainpulator)

catkin_install_python(PROGRAMS
  scripts/h5_udp_bridge_node.py
  DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
)

install(DIRECTORY launch
  DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
)
